### ISSUE TITLE
Multiple Drag and Drop

### ISSUE THREAD

**Issue by arias9306** [dlsc-software-consulting-gmbh/CalendarFX#38]
Hi @dlemmermann ,

Currently we are working in a new feature for the calendar component the drag and drop for multiple entries, but we are wondering if you agree if we could include this new feature in the calendar component

Current and expected behavior in these [videos](https://github.com/dlemmermann/CalendarFX/files/2376052/Multiple.DnD.zip)

**Comment by dlemmermann** [comment]
Yes, I think this would be a nice addition to CalendarFX.

**Comment by dlemmermann** [comment]
Any progress on this issue?

**Comment by dlemmermann** [comment]
Can I close this?

**Comment by arias9306** [comment]
Hi @dlemmermann 

actually, the feature is already implemented, but we have some problems with series events and in our implementation of the calendar, we do not allow that types of events, so we decide to stop the progress on this feature for the moment and that's the reason why we don't create the pull request yet.

**Comment by dlemmermann** [comment]
Closing this for now. If you ever find implement a solution that works with recurring events then please create a pull request.
