### ISSUE TITLE
Adapt iCal4j recurrence

### ISSUE THREAD

**Issue by mwkroening** [dlsc-software-consulting-gmbh/CalendarFX#50]
I was starting a follow up on #49 to remove any Joda-Time dependency from this project, as  "from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project" ([Joda-Time Home](https://www.joda.org/joda-time/)) and this library targets "JavaFX 8, 9, 10, and 11".

When looking at `CalendarFXRecurrence`, I wondered if the whole module could be replaced by the recurrence API of [iCal4j](https://github.com/ical4j/ical4j). iCal4j implements [RFC5545](https://tools.ietf.org/html/rfc5545) (Supersedes [RFC2445](https://tools.ietf.org/html/rfc2445)). It is already in the dependency tree as dependency of `CalendarFXiCal` and will adapt java.time (JSR-310) in the future (see https://github.com/ical4j/ical4j/issues/242).

What do you think about that?

**Comment by dlemmermann** [comment]
That sounds like a very good idea. However I am not sure how big the impact will be on the public API of CalendarFX. If it is also possible to express the entire recurrence via a single string ("rrule" on Entry) then this would be great.

**Comment by mkroening** [comment]
Resolved by #51.
